### ISSUE TITLE
Suggestion: View conflicts for "First/Second/Third/Fourth X of the Month"

### ISSUE THREAD

**Issue by loklaan** [AshKyd/eventsbne#6]
Hey Ash

I've noticed that _most_ meetups try to schedule around each other, for long periods of time, by using "First Monday of the Month" logic.

It'd be neat to see conflicts based on this logic.

Keep up the cool work!

**Comment by AshKyd** [comment]
Makes total sense. Reckon we could parse this out of the previous meetups? Or will it need to be a central registry?
